#!/usr/bin/env python3
"""把一键部署模板翻译成**等价的** docker compose · 可重复运行

为什么要有这个脚本
────────────────────────────────────────────────────────────────────────
我们没有任何一个平台的账号（M3 是 Zeabur / Sealos / 1Panel，M4 又加了 Railway /
Coolify / Dokploy），没法在真实平台上点一次部署。
但模板里真正会出错的东西 —— 镜像标签、环境变量名、密钥怎么生成、谁和谁必须
同值、卷挂在哪、依赖顺序 —— 和平台本身关系不大。所以这里把模板**机械地**
翻译成 compose：同样的镜像、同样的环境变量、**用平台自己的方式生成的随机密钥**、
同样的卷和依赖，然后在本机从空卷跑一遍，走完向导 + 真实对话。

翻译是机械的 = 人不能在中间「顺手改一下」。脚本读模板、写 compose，
测试跑的就是模板本身的语义。

**加新平台时先问一句:这个平台的卷是什么语义。** M4 最值钱的两个发现都来自这里 ——
Docker 具名卷会把镜像里该路径的内容拷进空卷、根目录没有 lost+found、`depends_on`
还能编排启动顺序;这三条云平台上一条都不成立。Railway 的翻译因此**刻意模拟**了
「空卷 + ext4 的 lost+found + 没有启动顺序」,才把两个必炸的配置炸出来。
拿本机 Docker 的语义当基准一定会漏。

不能覆盖到的（老实写在这里，成果文档里也会列）：
  · 平台控制台的表单渲染、域名绑定、计费、镜像拉取加速、反代的 SSE 超时
  · Zeabur 的 ${PASSWORD} 到底是不是「每服务一个」（按官方文档实现）
  · Sealos 的 KubeBlocks Cluster → 这里换成等价的官方镜像跑
  · K8s 的 Ingress 注解、HPA、亲和性
  · Railway 的引用变量能不能引用到 secret() 生成的值（按官方文档实现）
  · Coolify 的 magic 变量字符集、Dokploy 的 Isolated Deployments 开关

用法
────────────────────────────────────────────────────────────────────────
    python3 deploy/tools/template-to-compose.py zeabur  --out /tmp/t/zeabur
    python3 deploy/tools/template-to-compose.py sealos  --out /tmp/t/sealos
    python3 deploy/tools/template-to-compose.py 1panel  --out /tmp/t/1panel
    python3 deploy/tools/template-to-compose.py railway --out /tmp/t/railway
    python3 deploy/tools/template-to-compose.py coolify --out /tmp/t/coolify
    python3 deploy/tools/template-to-compose.py dokploy --out /tmp/t/dokploy

每次生成一份新的随机密钥（和平台上每次部署一样）。加 --seed 可复现。
生成物：<out>/docker-compose.yml 和 <out>/SECRETS.txt（打码后的密钥来源说明）。

⚠️ **Sealos 要固定 --seed 才能反复清理干净**：它的 `defaults.app_name` 里带
`${{ random(8) }}`，服务名跟着变，不给 seed 就重新生成会得到一整套**新名字**的
服务 —— 这时 `docker compose down -v` 清的是新名字那套，上一套还在后台跑着占端口。
"""
from __future__ import annotations

import argparse
import json
import random
import re
import secrets
import string
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
ALPHABET = string.ascii_letters + string.digits


# ══════════════════════════════════════════════════════════════════════
# 随机值生成 —— 三个平台各自的方式
# ══════════════════════════════════════════════════════════════════════
class Rng:
    """可复现的随机源。--seed 给定时用 random，否则用 secrets。"""

    def __init__(self, seed: int | None):
        self._r = random.Random(seed) if seed is not None else None

    def token(self, length: int) -> str:
        if self._r is None:
            return "".join(secrets.choice(ALPHABET) for _ in range(length))
        return "".join(self._r.choice(ALPHABET) for _ in range(length))


# Zeabur 的 ${PASSWORD}：官方特殊变量文档原文 "A random password generated by
# Zeabur for each service" —— 每个服务一个，长度未公开，这里取 32。
ZEABUR_PASSWORD_LEN = 32


# ── 容器内探针命令 ─────────────────────────────────────────────────────
# ⚠️ 必须在**所有镜像里都能跑**。
#
# Zeabur 的 healthCheck 和 K8s 的 probe 都是平台从容器**外面**探的，对镜像里
# 有什么工具没有要求；compose 的 healthcheck 却在容器**里面**跑。翻译时只写
# curl，就等于凭空给模板加了一条它并不需要的依赖 —— M3 实测 llm-shim 镜像
# (74 MB) 没有 curl，服务被判 unhealthy，而它自己
# urllib.urlopen('/health') 返回的是 200。
def http_probe(port: int, path: str) -> str:
    """看返回码：curl --fail / urllib / wget 对非 2xx 都是非零退出。"""
    url = f"http://127.0.0.1:{port}{path}"
    return (
        f"curl -fsS --max-time 3 {url} >/dev/null 2>&1 "
        f"|| python3 -c \"import urllib.request as u;u.urlopen('{url}',timeout=3)\" 2>/dev/null "
        f"|| wget -q -O /dev/null {url} 2>/dev/null "
        f"|| exit 1"
    )


def tcp_probe(port: int) -> str:
    """只看端口连不连得上，**不看返回码**（opencode 的 / 本来就不是 200）。

    nc 在 alpine（postgres / redis）里有；python3 兜底用裸 socket。
    """
    return (
        f"nc -z 127.0.0.1 {port} 2>/dev/null "
        f"|| curl -sS -o /dev/null --max-time 3 http://127.0.0.1:{port}/ 2>/dev/null "
        f"|| python3 -c \"import socket;socket.create_connection(('127.0.0.1',{port}),3).close()\" 2>/dev/null "
        f"|| exit 1"
    )


def mask(v: str) -> str:
    return f"{v[:3]}****{v[-2:]}（{len(v)} 字符）" if len(v) > 8 else "****"


# ══════════════════════════════════════════════════════════════════════
# Zeabur
# ══════════════════════════════════════════════════════════════════════
VAR_RE = re.compile(r"\$\{([A-Za-z0-9_]+)\}")


def translate_zeabur(rng: Rng, web_port: int, debug_ports: bool) -> tuple[dict, list[str]]:
    doc = yaml.safe_load((ROOT / "deploy/zeabur/template.yaml").read_text(encoding="utf-8"))
    services = doc["spec"]["services"]
    notes: list[str] = []

    # 1) 每个服务一把 ${PASSWORD}
    passwords = {s["name"]: rng.token(ZEABUR_PASSWORD_LEN) for s in services}

    # 2) 每个服务的本地变量：端口 ID → ${<ID>_PORT}，CONTAINER_HOSTNAME = 服务名
    #    （compose 里服务名就是 DNS 名，和 Zeabur 私有网络的 <服务名>.zeabur.internal
    #     语义一致；下面会把 .zeabur.internal 后缀剥掉）
    local: dict[str, dict[str, str]] = {}
    for s in services:
        env = {"PASSWORD": passwords[s["name"]], "CONTAINER_HOSTNAME": s["name"]}
        for p in s["spec"].get("ports") or []:
            env[f"{p['id'].upper()}_PORT"] = str(p["port"])
        local[s["name"]] = env

    # 3) 迭代求值：先各服务内部，再把 expose 的放进全局池
    resolved: dict[str, dict[str, str]] = {s["name"]: {} for s in services}
    exposed: dict[str, str] = {}

    def subst(text: str, scope: dict[str, str]) -> tuple[str, bool]:
        done = True

        def rep(m):
            nonlocal done
            key = m.group(1)
            if key in scope:
                return scope[key]
            done = False
            return m.group(0)

        return VAR_RE.sub(rep, text), done

    for _ in range(10):  # 迭代到不动点
        changed = False
        for s in services:
            name = s["name"]
            scope = {**exposed, **local[name], **resolved[name]}
            for k, v in (s["spec"].get("env") or {}).items():
                raw = str(v.get("default", ""))
                out, _ = subst(raw, scope)
                if resolved[name].get(k) != out:
                    resolved[name][k] = out
                    changed = True
                if v.get("expose") and "${" not in out and exposed.get(k) != out:
                    exposed[k] = out
                    changed = True
        if not changed:
            break

    leftover = {
        f"{n}.{k}": v for n, e in resolved.items() for k, v in e.items() if "${" in v
    }
    if leftover:
        raise SystemExit(f"❌ 有变量没解析出来（模板写错了）：{json.dumps(leftover, ensure_ascii=False)}")

    # 4) 生成 compose
    out: dict = {"name": "hunter-tpl-zeabur", "services": {}, "volumes": {}}
    for s in services:
        name = s["name"]
        spec = s["spec"]
        env = dict(resolved[name])
        # Zeabur 私有网络主机名 <服务名>.zeabur.internal → compose 里就是服务名
        for k, v in env.items():
            env[k] = v.replace(".zeabur.internal", "")
        svc: dict = {
            "image": spec["source"]["image"],
            "restart": "unless-stopped",
            "environment": env,
        }
        if spec["source"].get("command"):
            svc["command"] = spec["source"]["command"]

        vols = []
        for v in spec.get("volumes") or []:
            vol = f"zb_{name.replace('-', '_')}_{v['id']}"
            out["volumes"][vol] = None
            vols.append(f"{vol}:{v['dir']}")
        if vols:
            svc["volumes"] = vols

        # Zeabur 的 dependencies 只管启动顺序，不等健康 —— 照搬成不带 condition 的
        # depends_on。这恰好是云平台上的真实情形：api 会先于 postgres 就绪启动，
        # 靠 M1 加的 connect_with_retry 顶住（apps/api/app/migrate.py）。
        deps = list(s.get("dependencies") or [])

        # init 规则 → 一次性 init 服务 + service_completed_successfully
        for rule in spec.get("init") or []:
            init_name = f"{name}-init-{rule['id']}"
            init_vols = []
            for m in rule.get("volumes") or []:
                vol = f"zb_{name.replace('-', '_')}_{m['id']}"
                init_vols.append(f"{vol}:{m['mountPath']}")
            out["services"][init_name] = {
                "image": rule.get("image", spec["source"]["image"]),
                "command": rule["command"],
                "volumes": init_vols,
                "restart": "no",
            }
            svc.setdefault("depends_on", {})
            if isinstance(deps, list):
                svc["depends_on"] = {d: {"condition": "service_started"} for d in deps}
                deps = []
            svc["depends_on"][init_name] = {"condition": "service_completed_successfully"}
            notes.append(f"init 规则 {rule['id']} → 一次性服务 {init_name}（等它跑完 {name} 才起）")
        if deps:
            svc["depends_on"] = deps

        # 端口：只有绑域名的 HTTP 端口对外，和模板里 portForwarding.enabled=false 一致
        ports = []
        for p in spec.get("ports") or []:
            if p["type"] == "HTTP":
                ports.append(f"{web_port}:{p['port']}")
            elif debug_ports:
                ports.append(f"{p['port']}")
        if ports:
            svc["ports"] = ports

        hc = spec.get("healthCheck")
        if hc:
            port = next(p["port"] for p in spec["ports"] if p["id"] == hc["port"])
            test = (http_probe(port, hc["http"]["path"]) if hc["type"] == "HTTP"
                    else tcp_probe(port))
            svc["healthcheck"] = {
                "test": ["CMD-SHELL", test],
                "interval": "10s",
                "timeout": "5s",
                "retries": 12,
                "start_period": "20s",
            }
        out["services"][name] = svc

    secret_note = [
        "Zeabur · 模板里的四个随机密钥由 ${PASSWORD} 生成（每个服务一把）：",
        f"  postgres.POSTGRES_PASSWORD   = {mask(passwords['postgres'])}",
        f"  redis.HUNTER_SETUP_TOKEN     = {mask(passwords['redis'])}",
        f"  llm-shim.JWT_SECRET          = {mask(passwords['llm-shim'])}",
        f"  api.HUNTER_INTERNAL_KEY      = {mask(passwords['api'])}",
        "四个值互不相同，且 api/opencode 拿到同一把 JWT_SECRET、api/web/opencode 拿到同一把 HUNTER_INTERNAL_KEY。",
    ]
    return out, secret_note + notes


# ══════════════════════════════════════════════════════════════════════
# Sealos
# ══════════════════════════════════════════════════════════════════════
SEALOS_EXPR = re.compile(r"\$\{\{\s*(.+?)\s*\}\}")
FAKE_NS = "ns-hunter"
FAKE_DOMAIN = "sealos.local"

# KubeBlocks Cluster → 等价的官方镜像
KB_IMAGES = {
    "postgresql": "postgres:16-alpine",
    "redis": "redis:7-alpine",
}


def translate_sealos(rng: Rng, web_port: int, debug_ports: bool) -> tuple[dict, list[str]]:
    text = (ROOT / "deploy/sealos/index.yaml").read_text(encoding="utf-8")
    # 条件渲染行不是合法 YAML，先按官方渲染器的做法剥掉（本模板没有用到）
    text = re.sub(r"^\s*\$\{\{\s*(if|else|endif)\b.*\}\}\s*$", "", text, flags=re.M)
    docs = [d for d in yaml.safe_load_all(text) if d]
    tmpl = next(d for d in docs if d.get("kind") == "Template")
    spec = tmpl["spec"]
    notes: list[str] = []

    # 1) 求值 defaults（random(N) 每处独立求值，官方 example.md 明写）
    env_scope: dict[str, str] = {}

    def eval_expr(expr: str) -> str:
        expr = expr.strip()
        if expr == "SEALOS_NAMESPACE":
            return FAKE_NS
        if expr == "SEALOS_CLOUD_DOMAIN":
            return FAKE_DOMAIN
        if expr == "SEALOS_CERT_SECRET_NAME":
            return "wildcard-cert"
        if expr == "SEALOS_SERVICE_ACCOUNT":
            return "sa-hunter"
        m = re.fullmatch(r"random\((\d+)\)", expr)
        if m:
            return rng.token(int(m.group(1)))
        if expr in env_scope:
            return env_scope[expr]
        raise SystemExit(f"❌ 不认识的 Sealos 表达式：${{{{ {expr} }}}}")

    def render(text_: str) -> str:
        prev = None
        cur = text_
        for _ in range(6):
            cur = SEALOS_EXPR.sub(lambda m: eval_expr(m.group(1)), cur)
            if cur == prev:
                break
            prev = cur
        return cur

    for key, item in (spec.get("defaults") or {}).items():
        env_scope[f"defaults.{key}"] = render(str(item["value"]))
    for key, item in (spec.get("inputs") or {}).items():
        # 没有人填表单 → 用 default（等价于用户直接点部署）
        env_scope[f"inputs.{key}"] = render(str(item.get("default", "")))

    app_name = env_scope["defaults.app_name"]
    rendered = [yaml.safe_load(render(yaml.safe_dump(d, allow_unicode=True))) for d in docs]

    # 2) 合成 KubeBlocks 会生成的那两个 Secret（本机用等价镜像跑，凭据我们自己定）
    pg_password = rng.token(24)
    redis_password = rng.token(24)
    secrets_map = {
        f"{app_name}-pg-conn-credential": {
            "host": f"{app_name}-pg",
            "port": "5432",
            "username": "postgres",
            "password": pg_password,
        },
        f"{app_name}-redis-redis-account-default": {
            "username": "default",
            "password": redis_password,
        },
    }

    out: dict = {"name": "hunter-tpl-sealos", "services": {}, "volumes": {}}

    # 3) Cluster → 等价镜像
    for d in rendered:
        if d.get("kind") != "Cluster":
            continue
        kind = d["spec"].get("clusterDefinitionRef")
        name = d["metadata"]["name"]
        image = KB_IMAGES[kind]
        vol = f"sl_{name.replace('-', '_')}_data"
        out["volumes"][vol] = None
        if kind == "postgresql":
            out["services"][name] = {
                "image": image,
                "restart": "unless-stopped",
                "environment": {
                    "POSTGRES_USER": "postgres",
                    "POSTGRES_PASSWORD": pg_password,
                    "POSTGRES_DB": "postgres",
                },
                "volumes": [f"{vol}:/var/lib/postgresql/data"],
                "healthcheck": {
                    "test": ["CMD-SHELL", "pg_isready -U postgres"],
                    "interval": "5s", "timeout": "3s", "retries": 20,
                },
            }
        else:
            out["services"][name] = {
                "image": image,
                "restart": "unless-stopped",
                "command": ["redis-server", "--requirepass", redis_password],
                "volumes": [f"{vol}:/data"],
                "healthcheck": {
                    "test": ["CMD", "redis-cli", "-a", redis_password, "ping"],
                    "interval": "5s", "timeout": "3s", "retries": 20,
                },
            }
        notes.append(f"KubeBlocks Cluster {name}（{kind}）→ 等价镜像 {image}")

    # redis 的 K8s Service 名是 <app>-redis-redis-redis，compose 里给个别名
    redis_svc = f"{app_name}-redis"
    if redis_svc in out["services"]:
        out["services"][redis_svc]["networks"] = {
            "default": {"aliases": [f"{app_name}-redis-redis-redis"]}
        }

    # 4) Deployment / StatefulSet → compose 服务
    ingress_backend, ingress_port = None, None
    for d in rendered:
        if d.get("kind") == "Ingress":
            b = d["spec"]["rules"][0]["http"]["paths"][0]["backend"]["service"]
            ingress_backend, ingress_port = b["name"], b["port"]["number"]

    for d in rendered:
        if d.get("kind") not in ("Deployment", "StatefulSet"):
            continue
        name = d["metadata"]["name"]
        pod = d["spec"]["template"]["spec"]
        c = pod["containers"][0]

        env: dict[str, str] = {}
        for e in c.get("env") or []:
            if "value" in e:
                val = str(e["value"])
            else:
                ref = e["valueFrom"]["secretKeyRef"]
                val = secrets_map[ref["name"]][ref["key"]]
            # K8s 的 $(VAR) 只认同一个列表里靠前的项，按这个语义展开
            val = re.sub(r"\$\(([A-Za-z0-9_]+)\)", lambda m: env.get(m.group(1), m.group(0)), val)
            # <svc>.<ns>.svc[.cluster.local] → compose 里就是服务名
            val = re.sub(rf"\.{re.escape(FAKE_NS)}\.svc(\.cluster\.local)?", "", val)
            env[e["name"]] = val

        svc: dict = {"image": c["image"], "restart": "unless-stopped", "environment": env}

        # volumeClaimTemplates → 具名卷。fsGroup 有值时补一个 init 服务，
        # 模拟 K8s「PVC 是空目录 + fsGroup 改属主」的语义 —— Docker 具名卷
        # 会把镜像里的内容连属主一起拷进来，不清空的话就测不到 R0 发现的那个坑。
        fsgroup = (pod.get("securityContext") or {}).get("fsGroup")
        mounts = {m["name"]: m["mountPath"] for m in (c.get("volumeMounts") or [])}
        vols = []
        for vct in d["spec"].get("volumeClaimTemplates") or []:
            vname = vct["metadata"]["name"]
            vol = f"sl_{name.replace('-', '_')}_{vname}"
            out["volumes"][vol] = None
            vols.append(f"{vol}:{mounts[vname]}")
            if fsgroup:
                init_name = f"{name}-init-{vname}"
                out["services"][init_name] = {
                    "image": "busybox:1.36",
                    "restart": "no",
                    "volumes": [f"{vol}:/mnt/vol"],
                    "command": [
                        "/bin/sh", "-c",
                        # 模拟 K8s：**只有第一次**是空 PVC，之后每次 Pod 启动
                        # fsGroup 只改属主、不动内容。
                        #
                        # ⚠️ 第一版无条件 `rm -rf`，结果 `docker compose start`
                        # 会把这个一次性服务也拉起来，每次重启都清一遍卷 ——
                        # 重启后会话数从 5 变成 0，看着像「数据丢了」，其实是
                        # 测试脚手架自己删的。K8s 的 fsGroup 从不删数据，
                        # 照搬那种写法测出来的结论是假的。
                        "if [ ! -f /mnt/vol/.m3-pvc-init ]; then "
                        "rm -rf /mnt/vol/* /mnt/vol/.[!.]* 2>/dev/null; "
                        "touch /mnt/vol/.m3-pvc-init; echo '[init] 全新 PVC：已清空'; "
                        "else echo '[init] 已有 PVC：只改属主，不动内容'; fi; "
                        f"chown -R 0:{fsgroup} /mnt/vol && chmod -R g+rwX /mnt/vol && ls -la /mnt/vol",
                    ],
                }
                svc.setdefault("depends_on", {})[init_name] = {
                    "condition": "service_completed_successfully"
                }
                notes.append(
                    f"{name} 的 securityContext.fsGroup={fsgroup} → init 服务 {init_name}"
                    f"（清空卷模拟全新 PVC + chown 到 GID {fsgroup}）"
                )
        if vols:
            svc["volumes"] = vols

        # K8s 探针 → compose healthcheck
        probe = c.get("readinessProbe") or c.get("startupProbe")
        if probe and "httpGet" in probe:
            g = probe["httpGet"]
            test = http_probe(g["port"], g["path"])
        elif probe and "tcpSocket" in probe:
            test = tcp_probe(probe["tcpSocket"]["port"])
        else:
            test = None
        if test:
            svc["healthcheck"] = {
                "test": ["CMD-SHELL", test],
                "interval": "10s", "timeout": "5s", "retries": 30, "start_period": "20s",
            }

        ports = []
        if name == ingress_backend:
            ports.append(f"{web_port}:{ingress_port}")
        elif debug_ports:
            ports += [str(p["containerPort"]) for p in (c.get("ports") or [])]
        if ports:
            svc["ports"] = ports

        out["services"][name] = svc

    secret_note = [
        "Sealos · 密钥由 ${{ random(N) }} 在 defaults 里生成（每处独立求值）：",
        f"  defaults.jwt_secret     = {mask(env_scope['defaults.jwt_secret'])}",
        f"  defaults.internal_key   = {mask(env_scope['defaults.internal_key'])}",
        f"  inputs.setup_token      = {mask(env_scope['inputs.setup_token'])}",
        f"  postgres（KubeBlocks 代生成，本机用等价镜像）= {mask(pg_password)}",
        f"  redis（同上）= {mask(redis_password)}",
        f"  应用名 defaults.app_name = {app_name}",
    ]
    return out, secret_note + notes


# ══════════════════════════════════════════════════════════════════════
# 1Panel
# ══════════════════════════════════════════════════════════════════════
def translate_1panel(rng: Rng, web_port: int, debug_ports: bool) -> tuple[dict, list[str]]:
    base = ROOT / "deploy/1panel/hunter-community"
    if not base.exists():
        raise SystemExit("❌ deploy/1panel/hunter-community 不存在（并行子任务还没合并进来）")
    versions = sorted(p for p in base.iterdir() if p.is_dir())
    if not versions:
        raise SystemExit("❌ 1Panel 应用包里没有版本目录")
    vdir = versions[-1]
    notes = [f"1Panel · 用版本目录 {vdir.name}"]

    # 表单字段：random 类型由面板生成，其余取 default
    form_file = vdir / "data.yml"
    if not form_file.exists():
        form_file = base / "data.yml"
    form = yaml.safe_load(form_file.read_text(encoding="utf-8")) or {}
    fields = (form.get("additionalProperties") or {}).get("formFields") or form.get("formFields") or []

    values: dict[str, str] = {}
    for f in fields:
        key = f.get("envKey") or f.get("key")
        if not key:
            continue
        # ⚠️ 1Panel **没有** `type: random`。随机是 `type: password` 上的
        # `random: true` 属性（子任务 E 查 1Panel-dev/appstore 真实应用核实，
        # 设计方案 5.1 / 5.5 原来的写法是错的）。长度由面板决定、未公开，
        # 这里取 16 —— 真实长度只有装一次看 .env 才知道，已列进待办。
        if f.get("random") is True:
            values[key] = rng.token(16)
            notes.append(f"表单字段 {key} · password + random:true → 本次生成 {mask(values[key])}")
        else:
            values[key] = str(f.get("default", ""))

    compose_text = (vdir / "docker-compose.yml").read_text(encoding="utf-8")
    # 1Panel 把表单值写进同目录的 .env，compose 用 ${KEY} 取 —— 这里直接代入
    # 面板内置变量：容器名前缀。1Panel 用它给每个容器加应用实例前缀，
    # 避免和面板上别的应用在共享的 1panel-network 上撞网络别名。
    values.setdefault("CONTAINER_NAME", "hunter1p")

    def sub(m):
        key, default = m.group(1), m.group(3)
        if key == "PANEL_APP_PORT_HTTP":
            return str(web_port)
        if key in values and values[key] != "":
            return values[key]
        return default if default is not None else ""

    compose_text = re.sub(r"\$\{([A-Za-z0-9_]+)(:-([^}]*))?\}", sub, compose_text)
    out = yaml.safe_load(compose_text)
    out["name"] = "hunter-tpl-1panel"
    return out, notes


# ══════════════════════════════════════════════════════════════════════
# Railway
# ══════════════════════════════════════════════════════════════════════
# Railway 没有「模板文件」——官方流程是在控制台里把项目跑通，再 Settings →
# Generate Template from Project 反向生成模板。所以这里读的是 deploy/railway/
# services.yaml：那是一张「要在控制台里敲什么」的逐字对照表（见该文件头部说明）。
RAILWAY_FN = re.compile(r"\$\{\{\s*(.+?)\s*\}\}")
RAILWAY_INTERNAL = re.compile(r"\b([A-Za-z0-9_-]+)\.railway\.internal\b")


def translate_railway(rng: Rng, web_port: int, debug_ports: bool) -> tuple[dict, list[str]]:
    doc = yaml.safe_load((ROOT / "deploy/railway/services.yaml").read_text(encoding="utf-8"))
    services = doc["services"]
    notes: list[str] = []
    by_name = {s["name"]: s for s in services}

    # 1) 先把每个服务的字面量变量收进来；${{...}} 留到第二遍解
    resolved: dict[str, dict[str, str]] = {}
    for s in services:
        env = {}
        for k, v in (s.get("variables") or {}).items():
            env[k] = str(v.get("value", ""))
        resolved[s["name"]] = env

    # 2) secret(n) / randomInt(a,b) —— 官方：每处独立求值，不是全局同一个值
    #    https://docs.railway.com/templates/create
    def eval_fn(expr: str) -> str | None:
        # secret(length?, alphabet?) · 官方默认 32 字符。本清单没用自定义字母表，
        # 真传了就按它给的字符集取，免得以后加了这里悄悄用错。
        m = re.fullmatch(r'secret\(\s*(\d+)?\s*(?:,\s*"([^"]*)"\s*)?\)', expr)
        if m:
            n = int(m.group(1) or 32)
            alpha = m.group(2)
            return rng.token(n) if not alpha else "".join(
                alpha[ord(c) % len(alpha)] for c in rng.token(n))
        # randomInt(min?, max?) · 默认 0~100。本清单没用到，留着是为了将来加了不会静默失效。
        m = re.fullmatch(r"randomInt\(\s*(\d+)?\s*(?:,\s*(\d+)\s*)?\)", expr)
        if m:
            lo, hi = int(m.group(1) or 0), int(m.group(2) or 100)
            return str(lo + sum(ord(c) for c in rng.token(8)) % (hi - lo + 1))
        return None

    for name, env in resolved.items():
        for k, v in list(env.items()):
            def rep(m, _name=name, _k=k):
                out = eval_fn(m.group(1))
                if out is None:
                    return m.group(0)
                return out
            env[k] = RAILWAY_FN.sub(rep, v)

    # 3) 引用变量 ${{Service.VAR}}。RAILWAY_PRIVATE_DOMAIN → compose 里的服务名
    #    （compose 的服务名就是网络别名，语义与 <服务名>.railway.internal 一致）
    for _ in range(10):
        changed = False
        for name, env in resolved.items():
            for k, v in list(env.items()):
                def rep(m):
                    expr = m.group(1)
                    if "." not in expr:
                        return m.group(0)
                    svc, var = expr.split(".", 1)
                    if var == "RAILWAY_PRIVATE_DOMAIN":
                        return svc
                    val = resolved.get(svc, {}).get(var)
                    return val if val is not None and "${{" not in val else m.group(0)
                new = RAILWAY_FN.sub(rep, v)
                if new != v:
                    env[k] = new
                    changed = True
        if not changed:
            break

    leftover = {f"{n}.{k}": v for n, e in resolved.items() for k, v in e.items() if "${{" in v}
    if leftover:
        raise SystemExit(f"❌ 有变量没解析出来（清单写错了）：{json.dumps(leftover, ensure_ascii=False)}")

    # 4) 写死的 <服务名>.railway.internal → compose 服务名
    for env in resolved.values():
        for k, v in env.items():
            env[k] = RAILWAY_INTERNAL.sub(lambda m: m.group(1), v)

    # 5) 生成 compose
    out: dict = {"name": "hunter-tpl-railway", "services": {}, "volumes": {}}
    for s in services:
        name = s["name"]
        env = dict(resolved[name])
        svc: dict = {"image": s["image"], "restart": "unless-stopped", "environment": env}

        # RAILWAY_RUN_UID=0 → 容器以 root 跑（Railway 的卷是 root 属主的，官方给的办法）
        uid = env.get("RAILWAY_RUN_UID")
        if uid is not None:
            svc["user"] = f"{uid}:{uid}"
            notes.append(f"{name} · RAILWAY_RUN_UID={uid} → compose user: {uid}:{uid}")

        vol = s.get("volume")
        if vol:
            vname = f"rw_{name}"
            out["volumes"][vname] = None
            svc["volumes"] = [f"{vname}:{vol['mountPath']}"]
            # ⚠️ Railway 的卷和 K8s 的 PVC 一样,挂上去就是个**空目录**;
            # 而 Docker 的具名卷首次挂载会把镜像里该路径的内容与属主拷进卷。
            # 不模拟这一条,「把卷挂到了镜像里本来有东西的路径上」这种错误在本机
            # 一点症状都没有,到了平台上才发现文件不见了(M4 实测踩过一次:
            # api 的卷原本挂在 /opt/hunter-data,那是随镜像分发的静态数据目录)。
            #
            # 只在**首次**清空(打一个 marker),否则 `docker compose start` 会把
            # 一次性服务也拉起来,每次重启都清一遍卷 —— M3 在 Sealos 的模拟上踩过。
            init_name = f"{name}-emptyvol"
            out["services"][init_name] = {
                "image": "busybox:1.36",
                "command": ["/bin/sh", "-c",
                            "[ -f /mnt/lost+found/.done ] && exit 0; "
                            "rm -rf /mnt/..?* /mnt/.[!.]* /mnt/* 2>/dev/null; "
                            # Railway 的卷是 ext4 块设备,根目录天生带 lost+found ——
                            # 少了它,「把卷直接当 PGDATA」这个必炸的配置在本机一点症状都没有
                            "mkdir -p /mnt/lost+found && touch /mnt/lost+found/.done; "
                            "echo '[init] 模拟 Railway 空卷(ext4 · 带 lost+found):已清空'"],
                "volumes": [f"{vname}:/mnt"],
                "restart": "no",
            }
            svc["depends_on"] = {init_name: {"condition": "service_completed_successfully"}}

        if s.get("public"):
            svc["ports"] = [f"{web_port}:{s['listenPort']}"]
        elif debug_ports:
            svc["ports"] = [str(s["listenPort"])]

        hcp = s.get("healthcheckPath")
        test = http_probe(s["listenPort"], hcp) if hcp else tcp_probe(s["listenPort"])
        svc["healthcheck"] = {
            "test": ["CMD-SHELL", test],
            "interval": "10s", "timeout": "5s", "retries": 12, "start_period": "20s",
        }
        out["services"][name] = svc

    # Railway **没有**服务间的启动顺序编排：六个服务同时起。这里照搬（不写 depends_on）——
    # 这恰恰是云平台上的真实情形，api 会先于 postgres 就绪启动，靠 connect_with_retry 顶住。
    notes.insert(0, "Railway 无启动顺序编排 → 生成的 compose 里**没有 depends_on**，六个服务同时起")

    api_env = resolved["api"]
    notes.append(
        "Railway · 三把密钥由 ${{secret(N)}} 在部署时生成（每处独立求值）："
        f"JWT_SECRET={mask(api_env['JWT_SECRET'])} · "
        f"HUNTER_INTERNAL_KEY={mask(api_env['HUNTER_INTERNAL_KEY'])} · "
        f"HUNTER_SETUP_TOKEN={mask(api_env['HUNTER_SETUP_TOKEN'])}；"
        "opencode / web 用引用变量 ${{api.X}} 取同一个值"
    )
    notes.append("监听地址全部设成 `::`（Railway 老环境私有网络 IPv6-only）——"
                 "这一套等价栈就是在验证四个镜像绑 `::` 之后还能不能互通")
    return out, notes


# ══════════════════════════════════════════════════════════════════════
# Coolify / Dokploy
# ══════════════════════════════════════════════════════════════════════
# 这两家「模板」本身就是一份 docker compose —— 平台把它原样交给 docker compose 跑。
# 所以翻译要做的只有一件事:**按平台自己的规则把变量填上**，别的一个字都不改。
#   · Coolify：magic 变量由平台生成并持久化
#       SERVICE_PASSWORD_<ID>    32 位随机口令(不含符号)
#       SERVICE_PASSWORD_64_<ID> 64 位
#       SERVICE_USER_<ID>        16 位随机用户名
#       SERVICE_FQDN_<服务>_<端口> / SERVICE_URL_<服务>_<端口>  平台分配的域名
#       https://coolify.io/docs/knowledge-base/docker/compose
#   · Dokploy：**没有**自动生成，用户在 Environment 页签里填，平台写进同目录 .env，
#       compose 的 ${VAR} 插值读它。这里就模拟「用户自己 openssl rand 一把」。
#       https://docs.dokploy.com/docs/core/docker-compose
COOLIFY_MAGIC = re.compile(
    r"\$\{(SERVICE_(?:FQDN|URL|PASSWORD_64|PASSWORD|USER|BASE64)_[A-Z0-9_]+)\}")
PLAIN_VAR = re.compile(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}")
FAKE_FQDN = "hunter.example.test"


def _paas_common(path: str, project: str, resolve, rng: Rng,
                 web_port: int, debug_ports: bool) -> tuple[dict, list[str]]:
    notes: list[str] = []
    seen: dict[str, str] = {}

    def sub(m):
        key = m.group(1)
        if key not in seen:
            val = resolve(key)
            if val is None:
                raise SystemExit(f"❌ 变量 {key} 没人给值 —— 平台不会生成它,文档里也没让用户填")
            seen[key] = val
            notes.append(f"{key} → {mask(val) if 'PASSWORD' in key or 'TOKEN' in key else val}")
        return seen[key]

    # ⚠️ 先 load 再替换,**不要在原始文本上替换** —— 文件头的注释里就写着
    # 「compose 的 ${VAR} 插值读它」这种句子,在文本上替换会把注释里的 ${VAR}
    # 也当成一个真变量,然后报「没人给值」。YAML 解析完注释自然就没了。
    out = yaml.safe_load((ROOT / path).read_text(encoding="utf-8"))

    def walk(node):
        if isinstance(node, str):
            return PLAIN_VAR.sub(sub, COOLIFY_MAGIC.sub(sub, node))
        if isinstance(node, list):
            return [walk(x) for x in node]
        if isinstance(node, dict):
            return {k: walk(v) for k, v in node.items()}
        return node

    out = walk(out)
    out["name"] = project

    # 平台的反代按域名把流量送进 web 的 3000;本机没有反代,给 web 映一个宿主端口。
    # 其余服务一律不映射 —— 与这两个平台上的实际情形一致(只有绑了域名的服务对外)。
    out["services"]["web"].setdefault("ports", []).append(f"{web_port}:3000")
    if debug_ports:
        for name, port in (("api", 8000), ("opencode", 3901), ("llm-shim", 3999),
                           ("postgres", 5432), ("redis", 6379)):
            out["services"][name].setdefault("ports", []).append(str(port))

    # 具名卷在这两个平台上由 docker 自己管(Coolify 只在 Persistent Storage 里只读展示),
    # 翻译时原样保留 —— 这正是「compose 语义平台」相对 K8s 的优势,不需要任何模拟。
    notes.append("卷:原样保留 compose 的具名卷(这两家就是把文件交给 docker compose 跑)")
    return out, notes


def translate_coolify(rng: Rng, web_port: int, debug_ports: bool) -> tuple[dict, list[str]]:
    def resolve(key: str) -> str | None:
        if key.startswith("SERVICE_PASSWORD_64_"):
            return rng.token(64)
        if key.startswith("SERVICE_PASSWORD_"):
            return rng.token(32)          # 官方:32 位、不含符号
        if key.startswith("SERVICE_USER_"):
            return rng.token(16)
        if key.startswith("SERVICE_BASE64_"):
            return rng.token(32)
        if key.startswith(("SERVICE_FQDN_", "SERVICE_URL_")):
            return FAKE_FQDN              # 本机没有反代,这个值只是被写进环境变量
        return None

    out, notes = _paas_common("deploy/coolify/docker-compose.yml", "hunter-tpl-coolify",
                              resolve, rng, web_port, debug_ports)
    notes.insert(0, "Coolify · 随机值由平台的 magic 变量生成并持久化(重新部署不变)")
    notes.append("JWT_SECRET / HUNTER_INTERNAL_KEY 不在 compose 里 —— "
                 "由 api 首启生成写进 hunter_secrets 卷,web/opencode 只读挂同一个卷")
    return out, notes


def translate_dokploy(rng: Rng, web_port: int, debug_ports: bool) -> tuple[dict, list[str]]:
    # Dokploy 没有随机值生成器,文档让用户自己 `openssl rand`。这里就照办。
    def resolve(key: str) -> str | None:
        if key == "POSTGRES_PASSWORD":
            return rng.token(48)          # openssl rand -hex 24
        if key == "HUNTER_SETUP_TOKEN":
            return rng.token(24)          # openssl rand -hex 12
        return None

    out, notes = _paas_common("deploy/dokploy/docker-compose.yml", "hunter-tpl-dokploy",
                              resolve, rng, web_port, debug_ports)
    notes.insert(0, "Dokploy · 两个值由用户在 Environment 页签里填(平台写进 .env,"
                    "compose 的 ${VAR} 插值读它);这里模拟用户 openssl rand 生成")
    return out, notes


# ══════════════════════════════════════════════════════════════════════
TRANSLATORS = {
    "zeabur": translate_zeabur,
    "sealos": translate_sealos,
    "1panel": translate_1panel,
    "railway": translate_railway,
    "coolify": translate_coolify,
    "dokploy": translate_dokploy,
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("platform", choices=sorted(TRANSLATORS))
    ap.add_argument("--out", required=True, help="输出目录")
    ap.add_argument("--web-port", type=int, default=3200, help="web 映射到宿主的端口（默认 3200，预发栈用）")
    ap.add_argument("--debug-ports", action="store_true", help="把内部服务端口也映出来（默认不映，与模板一致）")
    ap.add_argument("--seed", type=int, default=None, help="固定随机种子以复现（默认每次都是新的真随机）")
    ap.add_argument("--project", default=None,
                    help="compose 项目名（写进 name:）。默认 hunter-tpl-<平台>。"
                         "同时跑多套时**必须各给一个** —— 否则 `docker compose exec` "
                         "会按文件里的 name: 找到另一套，拿到别人的口令（M3 踩过）。")
    ap.add_argument("--tag", default=None,
                    help="把四个 hunter-community 镜像的标签换掉。**只给升级测试用** —— "
                         "先用老标签起一套、灌数据，再用新标签重新生成并 up -d，验证自动迁移与数据保留。"
                         "日常不要用：模板里钉的版本才是要发布的那一版。")
    args = ap.parse_args()

    rng = Rng(args.seed)
    compose, notes = TRANSLATORS[args.platform](rng, args.web_port, args.debug_ports)

    if args.project:
        compose["name"] = args.project

    if args.tag:
        n = 0
        for name, svc in compose["services"].items():
            img = svc.get("image", "")
            if "hunter-community-" in img and ":" in img:
                svc["image"] = img.rsplit(":", 1)[0] + ":" + args.tag
                n += 1
        notes.append(f"⚠ --tag {args.tag}：{n} 个自家镜像的标签被换掉（升级测试用，不是模板里的版本）")

    outdir = Path(args.out)
    outdir.mkdir(parents=True, exist_ok=True)
    header = (
        f"# 由 deploy/tools/template-to-compose.py 从 {args.platform} 模板自动翻译而来。\n"
        f"# ⚠️ 不要手工编辑 —— 要改就改模板再重新生成，否则测的就不是模板了。\n"
        f"# 重新生成：python3 deploy/tools/template-to-compose.py {args.platform} --out {args.out}\n"
    )
    (outdir / "docker-compose.yml").write_text(
        header + yaml.safe_dump(compose, allow_unicode=True, sort_keys=False, width=200),
        encoding="utf-8",
    )
    (outdir / "SECRETS.txt").write_text("\n".join(notes) + "\n", encoding="utf-8")

    print(f"✅ {args.platform} → {outdir/'docker-compose.yml'}")
    print(f"   服务 {len(compose['services'])} 个：{', '.join(compose['services'])}")
    for n in notes:
        print(f"   · {n}")
    print(f"\n真实密钥值不打印也不落盘明文说明，见容器环境变量。摘要写在 {outdir/'SECRETS.txt'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
